### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by victorgsp**
Updated readme.md to add directly link to the article

### CODE REVIEW

**Comment by victorgsp** [comment]
You can use https://stackedit.io/app# to improve your readme.md file.

**Comment by igsufpe** [comment]
> Readme.md atualizado para adicionar link direto ao artigo

Muito obrigado @victorgsp pela sugestão!

**Comment by igsufpe** [comment]
> You can use https://stackedit.io/app# to improve your readme.md file.

I'll take a look at StackEdit, thanks for the suggestion @victorgsp!

**Review by igsufpe — COMMENTED** [review]
Thanks a lot @victorgsp for the suggestion!

**Pull request closed without merging**
